---
# handlers file for web_share_ubuntu

- name: Reload angie
  ansible.builtin.systemd_service:
    name: angie
    state: reloaded

- name: Start nginx
  ansible.builtin.systemd_service:
    name: nginx
    state: started

- name: Restart nginx
  ansible.builtin.systemd_service:
    name: nginx
    state: restarted

- name: Reload nginx
  ansible.builtin.systemd_service:
    name: nginx
    state: reloaded

- name: Restart php
  ansible.builtin.systemd_service:
    name: '{{ item }}'
    state: restarted
  loop:
    - phpsessionclean
    - "php{{ php_fpm.vers }}-fpm"

- name: Restart vsftpd
  ansible.builtin.systemd_service:
    name: vsftpd
    state: restarted
