---
# defaults file for web_share_ubuntu

common:
  root_web: "www-data"
  root_sys: "root"
  dir_website: "/srv"
  net:
    full_fqdn: "test.local"
    protocol: "http"

angie:
  repo: 
    key_sign: "https://angie.software/keys/angie-signing.gpg"
  list_soft:
    - angie
  list_mod:
    - angie-module-echo
    - angie-module-cache-purge
  conf:
    srv: "/etc/angie/angie.conf"
    srv_templ: "s_angie/conf_srv/angie.j2"
    page: "/etc/angie/http.d/default.conf"
    page_templ: "s_angie/conf_page/default.j2"
  websites:
    shared_dirs: "{{ common.dir_website }}/angie"
    default:
      name: "default"
      dir_templ: "s_angie/page"
      page_name: "index.html"
      header: 
        key: "X-Test-Request"
        value: "angie-test"
        status_def: 200
        status_expected: 200

nginx:
  repo:
    key: "https://nginx.org/keys/nginx_signing.key"
    key_file: "/usr/share/keyrings/nginx-archive-keyring.gpg"
  list_presoft:
    - curl
    - gnupg2
    - ca-certificates
    - lsb-release
    - ubuntu-keyring
  list_soft:
    - nginx
    - apache2-utils
    - python3-passlib
  sites_dir: "{{ common.dir_website }}/nginx"
  conf:
    site_anable: "/etc/nginx/sites-enabled"
    site_avail: "/etc/nginx/sites-available"
    srv: "/etc/nginx/nginx.conf"
    srv_templ: "s_nginx/conf_srv/nginx.j2"
    page: "/etc/nginx/conf.d/default.conf"
    page_name_def: "default.conf"
    page_templ_def: "s_nginx/conf_page/default.j2"
  log:
    dirs: "/var/log/nginx"
  websites:
    shared_dirs: "{{ common.dir_website }}/nginx"
    default:
      name: "default"
      dir_templ: "s_nginx/page"
      page_name: "index.html"
      header: 
        key: "X-Test-Request"
        value: "nginx-test"
        status_def: 200
        status_expected: 200

php_fpm:
  vers: "8.3"
  list_soft:
    - fpm
    - cli
    - cgi
    - mysql
    - pgsql
    - xml
    - curl
    - zip
    - fileinfo
    - imagick
  conf:
    srv_templ: "php/conf/php-fpm/php.ini"
  websites:
    shared_dirs: "{{ common.dir_website }}/php-fpm"
    php:
      name: "php-fpm"
      dir_templ: "php/page"
      page_name: "info.php"

ftp:
  user:
    id: 100500
    login: "userf"
    pass: "PaSWoRd"
  list_presoft:
    - whois
  list_soft:
    - vsftpd
  conf:
    srv: "/etc/vsftpd.conf"
    srv_templ: "s_vsftpd/vsftpd.j2"
  websites:
    ftp:
      name: "ftp"
      path_dir: "{{ common.dir_website }}"
      auth_basic_user_file: "/etc/nginx/ftp_web-access"
      external_dir: "/download"

ufw:
  list_services:
    - Nginx HTTP
    - Nginx HTTPS
    - ftp
    - Apache
    - Apache Secure
